#+title: Taslak

 #+begin_verse
 Proje Ana Alanı    : Yazılım
 Proje Tematik Alanı: Robotik Kodlama
 Proje Adı (Başlığı): Merge
 #+end_verse

[[./../../logo/logo-inkscp.svg]]

* Giriş
Gelişen teknoloji ile birlikte yazılım alanında kullanılan metotların karmaşıklaşması yazılan programların soyutlaştırılması
(abstraction[fn:: https://en.wikipedia.org/wiki/Abstraction_(computer_science)]) yazılım geliştiriciliğinin en temel ve önemli noktasıdır.

Bu soyutlama basamakları sayesinde çoğu bilgisayar yazılımcısı alt seviyede (low level[fn:: https://www.bbc.co.uk/bitesize/guides/z4cck2p/revision/2])
ne olduğuna vakıf olmasa bile bilgisayarlar için program geliştirebilmekte.

Bu soyutlama evresinin göze çarpan en önemli elemanlarından birisi de programlama dilleridir. [fn:: https://en.wikipedia.org/wiki/Programming_language]
Bu diller sayesinde makina seviyesinde ne olduğunu bilmeden makinalar ile kolay bir biçimde konuşabiliriz.

Ben de birden fazla programlama dilini bir arada kullanabilmek için merge meta programlama
dilini[fn:: Merge programlama dilinin matematiksel kısmı diğer programlama dillerine dayanabilecek biçimde büyük çoğunluğu soyutlanmış
biçimde tasarlanmıştır. Bu nedenle merge diğer programlama dillerinin üstünde (meta) bir programlama dilidir.] geliştirdim. Ana hedefim basit bir sözdizimi
(syntax [https://en.wikipedia.org/wiki/Syntax_(programming_languages)]) ile kolaylıkla kullanılanılabilen, mümkün olduğu kadar hızlı ve basit bir programlama
dili yazmaktı. [TODO: fix these grammatical mistakes]

Programlar arasında yapılacak olan veri paylaşımını mümkün olan en güvenli şekilde uygulayabilmek için günümüz modern işletim
sistemlerinde var olan protokollerden yararlandım. Önceliklerimden birisi performans olduğundan genel adı Inter Process Communication
Mekanizmalarından yararlandım (shared mem  + file io for testing purposes)

** Merge Geliştirme Aşamaları

*** Fikir
# TODO: put some stuff here
# Uzun süren fikir alışverişleri sonucunda köprü

*** Kaynak Kodu
Merge Programlama Dili Git proje organizasyon yazılımı ile Github bünyesinde geliştirilmiştir.

Merge Dilini geliştirirken özenle seçtiğimiz ana yazılım dili olan Rust'ın bize gelişim aşamasında sağladığı katkılardan bahsetmek isterim.

**** Cargo Paket Yöneticisi
Cargo[fn:: Rust programlama dilinin resmî paket yöneticisi, derleyicisi, proje organizasyon sistemi. [[https:doc.rust-lang.org/cargo/][(Cargo Book]])] Paket Yöneticisi sayesinde Merge yazılımını geliştirmek,
yayınlamak ve test etmek çok kolaylaşmıştır.
**** Yüksek Seviye Sözdizimi, Yüksek Performans
Sistem programlama dilleri arasında oldukça yeni olan Rust, üst üste 8 yıl en çok istenilen programlama dili[fn::] olarak öne çıkmıştır.
Bu başarısının arkasında [[https:doc.rust-lang.org/1.8.0/book/references-and-borrowing.html][Borrow Checker]] gibi inovatif programlama konseptleri sayesinde sahip olduğu yüksek seviye sözdizimidir. (high level syntax)
Performans ile Yüksek seviyeli programlama dillerinin iyi yanlarını barındıran rust sayesinde Merge, yüksek performans ve anlaşılabilir bir kod havuzuna[fn:: simple code base] sahiptir.
Özellikle yenilikçi proc-macro, cebirsel veri tipleri[fn:: ADT ([[https:en.wikipedia.org/wiki/Algebraic_data_type][Algebraic Data Types]])] gibi özellikler, Rust programlama dilini ilgi çekici hâle getirmektedir. [TODO: improve overall readibility in this section]
*** Dökümantasyon
Merge dökümanları genellikle emacs programı kullanılarak org dosya formatında yazıldığından pek çok dosya tipine çevrilebilmektedir[fn:: org-export modulünü kullanarak org dosyaları; markdown, latex, pdf, html gibi formatlara çevrilmektedir].

Merge için ayrıca bir internet sitesi açılmayı beklemektedir. [TODO: rewise]

** Merge Kullanım Alanları

*** Test Temelli Yazılım Geliştirme - Test Driven Development (TDD)

Yazılım geliştiricileri için önerilen alışkanlıklar arasında "birim testleri" (Unit Testing) ilk sıralarda bulunur.
Kısaca programınızı birimlere bölerek her birimin sağlıklı çalıştığından ve istenilen sonuçları verdiğinden emin olmak için yazılımcı tarafından testler yazılmasıdır.

Bilgisayar bilimcileri arasında çok yaygın olan bu birim testlerinin geliştirilmesini kolaylaştırmak adına bir çok kütüphane yazılmıştır.
Örnek olarak (C++ için) GTest ve Catch2 (Rust için) cargo test (Python için) PyUnit ve Pytest örnek verilebilir. [TODO: clean up]

*** Birden fazla bilgisayarın bir programı çalıştırması (Soket Tabanlı IPC - Socket Based IPC)

Bu senaryo, Merge programlama dilinin deneysel özelliklerinden birisi olup istisnai durumlar için faydalıdır.

**** Artı Yönleri
Bazı donanımsal kısıtlamalardan dolayı yazılımların istenilen biçimde çalışmadığı durumda Soket Tabanlı IPC komünikasyon
protokollerini kullanarak işlemci gücü, dahili hafıza birimlerinin kapasitesi, internet komünikasyon
paralelleştirmesi[fn:: birden fazla bilgisayar ile bir ya da birden çok erişim ağı ile bağlantı kurarak interneti maksimum etkiyle kullanabilmeyi sağlar]

**** Eksi Yönleri

Bilgisayarlar arası veri aktarımı, yeterli donanıma sahip olunmadığı zaman işleyiş süresi performansını (runtime performance) inanılmaz seviyede düşürebilir.

** Merge Standartları

Yeni bir programlama dili geliştirmenin en zor yanlarından birisi olan sürdürülebilirliği (maintainability) sağlamak adına belirli standartlar belirlememiz gerekti. Başta programın formatı olmak üzere pek çok konu üzerinde belirlediğimiz standartlar sayesinde merge kullandığınız işletim sistemine bağlı olmadan çalışabilmektedir.

*** Dosya Uzantısı

Merge meta programlama dilinin özelliklerini kullanmanın iki farklı yolu var: Merge ile program yazmak, Yazdığınız program hakkında Merge Derleyicisine (compiler) bilgi vermek.

Eğer Merge programı yazmak istiyorsanız `.mg`
Eğer Merge Derleyicisini kullanıyorsanız `.mg.<dil>` (`<dil>` yerine kullandığınız programlama dilinin uzantısını yazın. Örneğin Rust Programlama Dili için `.rs.mg` uzantısını kullanmalısınız)
